apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubetopo-backend
  namespace: kubetopo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubetopo-backend-pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubetopo-backend-pod-reader
subjects:
  - kind: ServiceAccount
    name: kubetopo-backend
    namespace: kubetopo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubetopo-backend-pod-reader
