apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubevisor-backend
  namespace: kubevisor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubevisor-backend-pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevisor-backend-pod-reader
subjects:
  - kind: ServiceAccount
    name: kubevisor-backend
    namespace: kubevisor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubevisor-backend-pod-reader
