apiVersion: v1
kind: ServiceAccount
metadata:
  name: beyla
  namespace: kubeflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: beyla
rules:
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "services", "nodes"]
    verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: beyla
subjects:
  - kind: ServiceAccount
    name: beyla
    namespace: kubeflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: beyla
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: beyla-config
  namespace: kubeflow
data:
  beyla-config.yml: |
    otel_traces_export:
      endpoint: http://otel-collector.kubeflow.svc.cluster.local:4318
    otel_metrics_export:
      endpoint: http://otel-collector.kubeflow.svc.cluster.local:4318
      features:
        - network
    network:
      enable: true
      source: socket_filter
    ebpf:
      context_propagation: disabled
    javaagent:
      enabled: false
    attributes:
      kubernetes:
        enable: true
      select:
        beyla_network_flow_bytes:
          include:
            - k8s.src.owner.name
            - k8s.src.namespace
            - k8s.dst.owner.name
            - k8s.dst.namespace
            - dst.port
    discovery:
      instrument:
        - k8s_namespace: default
          open_ports: 8081-8083,5432
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: beyla
  namespace: kubeflow
  labels:
    app: beyla
spec:
  selector:
    matchLabels:
      app: beyla
  template:
    metadata:
      labels:
        app: beyla
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: beyla
      containers:
        - name: beyla
          image: grafana/beyla:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          env:
            - name: BEYLA_CONFIG_PATH
              value: "/config/beyla-config.yml"
          volumeMounts:
            - name: beyla-config
              mountPath: /config
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: beyla-config
          configMap:
            name: beyla-config
