apiVersion: v1
kind: Service
metadata:
  name: kubeflow-backend
  namespace: kubeflow
  labels:
    app: kubeflow-backend
spec:
  type: ClusterIP
  selector:
    app: kubeflow-backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
