-- Initial schema: graph_snapshots table.
-- Compatible with both H2 (MODE=PostgreSQL) for local dev and PostgreSQL in-cluster.

CREATE TABLE graph_snapshots (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    captured_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    namespace     VARCHAR(255)             NOT NULL,
    snapshot_json TEXT                     NOT NULL
);

CREATE INDEX idx_graph_snapshots_captured_at
    ON graph_snapshots (captured_at);

CREATE INDEX idx_graph_snapshots_namespace_captured_at
    ON graph_snapshots (namespace, captured_at);
