apiVersion: v1
kind: ConfigMap
metadata:
  name: ticket-service-config
data:
  SPRING_PROFILES_ACTIVE: k8s
  DB_HOST: postgres
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  OTEL_SERVICE_NAME: ticket-service
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.kubevizor.svc.cluster.local:4318
  OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
  OTEL_TRACES_SAMPLER: parentbased_always_on
  OTEL_BSP_SCHEDULE_DELAY: "1000"
  OTEL_BSP_MAX_EXPORT_BATCH_SIZE: "512"
  OTEL_BSP_EXPORT_TIMEOUT: "5000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-service
  template:
    metadata:
      labels:
        app: ticket-service
    spec:
      containers:
        - name: ticket-service
          image: ticket-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: ticket-service-config
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 20
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 40
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-service
spec:
  type: NodePort
  selector:
    app: ticket-service
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30083
