spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:5432/ticketdb
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
